version: '2'
services:
  
  db:
    image: 'kartoza/postgis:11.0-2.5'
    restart: unless-stopped
    volumes:
      - postgres:/var/lib/postgresql
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASS=postgres
      - ALLOW_IP_RANGE=0.0.0.0/0  # To allow QGIS Desktop to connect to the DB
    networks:
      - net

  qgisserver:
    image: 'openquake/qgis-server:3.6.1'
    restart: unless-stopped
    environment:
      QGIS_SERVER_PARALLEL_RENDERING: 'true'
      QGIS_SERVER_MAX_THREADS: 4
      QGIS_SERVER_LOG_LEVEL: 0
      # needs to be defined as fcgi_param in nginx.conf
      # PGSERVICEFILE: /io/.pg_service.conf
    networks:
      - net
    volumes:
      # Data should be mount RO when working
      # with GeoPackages and more than one QGIS container
      - './projects:/io/data'
      - './conf/qgisserver-nginx.conf:/etc/nginx/nginx.conf'
      - './conf/nginx-cors-settings.conf:/etc/nginx/nginx-cors-settings.conf'            
#      - './app/prod:/var/www/data'
#      - './conf/qgisserver-nginx.conf:/etc/nginx/nginx.conf'
      - './conf/pg_service.conf:/io/.pg_service.conf'
#      - './conf/atlasprint/:/io/plugins/atlasprint/'
    ports:
      - '80:80'

networks:
  net:

volumes:
  postgres:
